# Generated by Django 4.2.16 on 2024-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='baseline',
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='baseline',
            field=models.FloatField(default=0),
        ),
    ]
