# Generated by Django 4.2.16 on 2024-12-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_flashcard_baseline_flashcardset_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.FloatField(default=86400),
        ),
    ]
