# Generated by Django 4.2.16 on 2025-01-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_flashcard_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='streak',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetition',
            field=models.IntegerField(default=1),
        ),
    ]
