# Generated by Django 4.2.16 on 2025-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_friendship_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='quickest_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
