# Generated by Django 4.2.16 on 2025-02-15 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_flashcardset_quickest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueuser',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
