# Generated by Django 4.2.16 on 2025-02-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_leagueuser_last_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueuser',
            name='last_reset',
        ),
    ]
