# Generated by Django 4.2.16 on 2025-02-15 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_league_last_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 17, 58, 0, 133599, tzinfo=datetime.timezone.utc)),
        ),
    ]
