# Generated by Django 4.2.16 on 2025-02-16 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_league_last_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='previous_top_users',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 15, 10, 47, 820994, tzinfo=datetime.timezone.utc)),
        ),
    ]
