# Generated by Django 4.2.16 on 2025-02-16 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_league_previous_top_users_alter_league_last_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 15, 56, 0, 225758, tzinfo=datetime.timezone.utc)),
        ),
    ]
