# Generated by Django 4.2.16 on 2025-02-16 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_league_last_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 16, 55, 56, 342842, tzinfo=datetime.timezone.utc)),
        ),
    ]
