# Generated by Django 4.2.16 on 2025-02-16 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_league_last_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 17, 0, 0, 244252, tzinfo=datetime.timezone.utc)),
        ),
    ]
