# Generated by Django 4.2.16 on 2025-03-13 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_league_last_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_rewarded',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 9, 13, 54, 294478, tzinfo=datetime.timezone.utc)),
        ),
    ]
